name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 1: Create S3 Bucket for Lambda Code
      - name: Ensure S3 Bucket for Lambda Exists
        run: |
          aws s3api head-bucket --bucket creationism-lambda-code || \
          aws s3api create-bucket --bucket creationism-lambda-code --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}

      # Step 2: Upload Lambda Code
      - name: Package and Upload Lambda Code
        run: |
          mkdir -p build
          zip -j build/stable_diffusion.zip lambda/stable_diffusion.py
          aws s3 cp build/stable_diffusion.zip s3://creationism-lambda-code/stable_diffusion.zip

      # Step 3: Deploy Remaining CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name creationism-stack \
            --template-file cfn/infrastructure.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
            LambdaCodeBucket=creationism-lambda-code \
            LambdaCodeKey=stable_diffusion.zip \
            HuggingFaceApiKey=${HUGGING_FACE_API_KEY}
