name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 1: Create S3 Bucket for Lambda Code
      - name: Ensure S3 Bucket for Lambda Exists
        run: |
          aws s3api head-bucket --bucket creationism-lambda-code || \
          aws s3api create-bucket --bucket creationism-lambda-code --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}

      # Step 2: Package Lambda Code with Dependencies
      - name: Package Lambda Code
        run: |
          mkdir -p build
          python3 -m venv build/venv
          source build/venv/bin/activate
          pip install requests boto3
          deactivate
          cp lambda/stable_diffusion.py build/
          cd build
          zip -r stable_diffusion.zip ./*
          TIMESTAMP=$(date +%s)
          export TIMESTAMPED_ZIP="stable_diffusion_${TIMESTAMP}.zip"
          mv stable_diffusion.zip "$TIMESTAMPED_ZIP"
          cd ..
          echo "TIMESTAMPED_ZIP=$TIMESTAMPED_ZIP" >> $GITHUB_ENV

      # Step 3: Upload Lambda Code to S3
      - name: Upload Lambda Code
        run: |
          aws s3 cp build/${{ env.TIMESTAMPED_ZIP }} s3://creationism-lambda-code/${{ env.TIMESTAMPED_ZIP }}

      # Step 4: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name creationism-stack \
            --template-file cfn/infrastructure.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
            LambdaCodeBucket=creationism-lambda-code \
            LambdaCodeKey=${{ env.TIMESTAMPED_ZIP }} \
            HuggingFaceApiKey=${HUGGING_FACE_API_KEY}
